### PR TITLE
Add notification for save attempt. [1318]

### PR DESCRIPTION
**Pull request by goudine**
Add notification modal for user after clicking save.
Does not check if save was successful.

### CODE REVIEW

**Comment by cuttlefish** [comment]
What's the point of this if it doesn't check that the story was saved? The message implies that the save was successful.

**Comment by goudine** [comment]
Out of scope of ticket. 
It implied local saving was functioning as expected but there are underlying issues.

Can either change description or close and create new tickets regarding state of local save

**Comment by cuttlefish** [comment]
Which ticket?

**Comment by goudine** [comment]
1318

**Comment by Coop56** [comment]
I'm still unable to replicate any underlying issues with saving.  I'll check this branch out and see what the notification looks like on a working instance - the notification should not display until the save is actually confirmed as being successful.

**Comment by Coop56** [comment]
Oh, I just looked at the code.  You don't want to call this function when you hit Save..that will send the notification immediately.  You want to call the function to display the modal upon a successful save.

**Comment by cuttlefish** [comment]
"currently the user isn't alerted when a save is successful or if it fails." This PR doesn't resolve that. It's better to do nothing.

**Pull request closed without merging**
