### PR TITLE
Shows a message to the user when saved

### PR DESCRIPTION
**Pull request by zunware**
- Implements the following behavior:
    + When a save completes without error,  a basic alert is shown.

screen shot 2018-08-07 at 2 04 59 pm

### CODE REVIEW

**Comment by zunware** [comment]
Improved modal:

screen shot 2018-08-07 at 2 04 59 pm

**Comment by cuttlefish** [comment]
Does this falsely claim success if something other that storypins fails?

**Comment by zunware** [comment]
@cuttlefish that would be correct. It does not check all promises for a 200, instead it relies on storypins save message to be OK.

**Comment by Coop56** [comment]
Two things I'd recommend before we merge this.  We need to make sure the entire save actually worked, before telling the user it was successful.  On top of that I don't think it needs to be a modal that the user closes.  I would suggest a notification in the top right that just fades away.  I think it would get annoying as a user to have to close a modal every time you save.  Curious to hear other's thoughts.  @jonpmarino @lhcramer?

**Comment by Coop56** [comment]
Closing this, the save refactor will handle this.  We just need to add the actual notification to it.

**Pull request closed without merging**
